# Generated by Django 4.2.5 on 2023-11-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_auto_20221203_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="mailchimp_tag",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Mailchimp Tag"
            ),
        ),
    ]
