# Generated by Django 5.0.7 on 2024-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_redirect", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrredirect",
            options={
                "ordering": ["target_url"],
                "verbose_name": "QR-Code",
                "verbose_name_plural": "QR-Codes",
            },
        ),
        migrations.AlterField(
            model_name="qrredirect",
            name="target_url",
            field=models.URLField(max_length=512),
        ),
    ]
