# Generated by Django 5.0.7 on 2024-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_redirect", "0002_alter_qrredirect_options_alter_qrredirect_target_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrredirect",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="qrredirect",
            name="target_url",
            field=models.URLField(max_length=512, verbose_name="Target URL"),
        ),
    ]
