# Generated by Django 3.2.13 on 2022-05-31 09:45

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0002_alter_tag_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
    ]
