# Generated by Django 5.0.7 on 2025-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="price_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe price",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe subscription",
            ),
        ),
    ]
