# Generated by Django 5.0.7 on 2025-06-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recurringdonation",
            old_name="stripe_data",
            new_name="extra_data",
        ),
        migrations.RenameField(
            model_name="recurringdonation",
            old_name="stripe_subscription_id",
            new_name="subscription_id",
        ),
        migrations.RenameField(
            model_name="singledonation",
            old_name="stripe_data",
            new_name="extra_data",
        ),
        migrations.RenameField(
            model_name="singledonation",
            old_name="stripe_payment_intent_id",
            new_name="payment_intent_id",
        ),
        migrations.RenameField(
            model_name="singledonation",
            old_name="stripe_transaction_id",
            new_name="transaction_id",
        ),
    ]
