# Generated by Django 5.0.7 on 2025-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0002_rename_stripe_data_recurringdonation_extra_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringdonation",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe payment intent ID",
            ),
        ),
        migrations.AlterField(
            model_name="recurringdonation",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="singledonation",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="singledonation",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("initialized", "Initialized"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
                verbose_name="State",
            ),
        ),
    ]
