# Generated by Django 5.0.7 on 2025-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_rename_extra_data_donation_payment_intent_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("succeeded", "Succeeded"),
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="State",
            ),
        ),
    ]
