# Generated by Django 5.0.7 on 2025-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_recurringdonation_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singledonation",
            name="transaction_id",
        ),
        migrations.AlterField(
            model_name="recurringdonation",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe payment intent",
            ),
        ),
        migrations.AlterField(
            model_name="recurringdonation",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="recurringdonation",
            name="subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe subscription",
            ),
        ),
        migrations.AlterField(
            model_name="singledonation",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe payment intent",
            ),
        ),
    ]
