# Generated by Django 5.0.7 on 2025-06-04 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0004_remove_singledonation_transaction_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringdonation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_donation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
