# Generated by Django 5.2.6 on 2025-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0004_alter_donation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="client_mode",
            field=models.CharField(
                choices=[("web", "Web"), ("app", "App")],
                db_index=True,
                default="web",
                max_length=16,
                verbose_name="Client mode",
            ),
        ),
    ]
