# Generated by Django 5.0.7 on 2025-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0005_alter_recurringdonation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringdonation",
            name="price_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=256,
                verbose_name="Stripe price",
            ),
        ),
    ]
