image: docker:latest

stages:
  - preflight
  - deploy

preflight-fe:
  stage: preflight
#  tags:
#    - node
  image: node:16-slim
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --dev
  script:
    - yarn lint

deploy:
  stage: deploy
  only:
    - main
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config gcp/build-migrate-deploy.yaml --async