#output-format: json

strictness: medium
test-warnings: true
doc-warnings: false

uses:
    - django

ignore-paths:
  - core/settings/
  - core/dev/
  - core/sync/management/

ignore-patterns:
  - (^|/)migrations?(/|$)
  - (^|/)tests?(/|$)

dodgy:
  run: true

profile-validator:
  run: true

frosted:
  run: false

pyflakes:
  run: true

vulture:
  run: false

pylint:
  run: true
  disable:
    - line-too-long # handled by Black
    - logging-format-interpolation
    - logging-fstring-interpolation
    - logging-too-many-args
    - relative-beyond-top-level # TODO: check
    - useless-suppression # TODO: check

pep8:
  run: false

mccabe:
  run: false
