version: "3"
services:
  nginx:
    build:
      context: ${PWD}/compose/nginx/
      dockerfile: ${PWD}/compose/nginx/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/dist:/var/www/static
    environment:
      IMAGE_RESIZER: image-resizer:8000
      CORE: core:8000
      STATIC: core:8000
      CDN_COOKIE_VALIDATOR: cdn-cookie-validator:8000
    networks:
      - obr
    depends_on:
      - core
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: obr
      POSTGRES_PASSWORD: obr
      POSTGRES_HOST_AUTH_METHOD: password
#    ports:
#      - "5434:5432"
    volumes:
      - obr-db:/var/lib/postgresql/data
    networks:
      - obr
  image-resizer:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/compose/image-resizer/Dockerfile
#    ports:
#      - "8180:8000"
    volumes:
      - ${PWD}/data:/data
    environment:
      SOURCE: fs:///data/media
    networks:
      - obr
  media-encoder:
    user: 1000:1000
    build:
      context: ${PWD}
      dockerfile: ${PWD}/compose/media-encoder/Dockerfile
    volumes:
      - ${PWD}/data:/data
    depends_on:
      - core
  core:
    user: 1000:1000
    command: ./manage.py runserver 0.0.0.0:8000
    build:
      context: ${PWD}
#      dockerfile: ${PWD}/compose/core/Dockerfile
      dockerfile: ${PWD}/docker/Dockerfile
    image: obr/core:lateest
    ports:
      - "8080:8000"
    volumes:
      - ${PWD}/data:/app/data
    env_file: ".env"
    environment:
      DEBUG: "yes"
      DJANGO_SETTINGS_MODULE: config.settings.env
      DATABASE_URL: psql://obr:obr@db:5432/obr
      # EMAIL_URL: smtp://mailhog:1025
      EMAIL_URL: consolemail://
    networks:
      - obr
    depends_on:
      - migrate
      - db
  sync-schedule:
    user: 1000:1000
    command: sh -c './manage.py sync_schedule -s $(date "+%Y-%m-%d") -i 300'
    image: obr/core:lateest
    volumes:
      - ${PWD}/data:/app/data
    env_file: ".env"
    environment:
      DATABASE_URL: psql://obr:obr@db:5432/obr
      OBP_SYNC_TOKEN: "${OBP_SYNC_TOKEN}"
      DJANGO_SETTINGS_MODULE: config.settings.env
    networks:
      - obr
    depends_on:
      - db
      - migrate
      - core
  migrate:
    user: 1000:1000
    command: ./manage.py migrate --noinput
    image: obr/core:lateest
    env_file: ".env"
    environment:
      DATABASE_URL: psql://obr:obr@db:5432/obr
      DJANGO_SETTINGS_MODULE: config.settings.env
    networks:
      - obr
    depends_on:
      - db
  cdn-cookie-validator:
    user: 1000:1000
    build:
      context: ${PWD}
      dockerfile: ${PWD}/compose/cdn-cookie-validator/Dockerfile
    ports:
      - "8008:8000"
    networks:
      - obr

volumes:
  obr:
  obr-db:

networks:
  obr:
