version: "3"
services:
  nginx:
    container_name: obr-nginx
    build:
      context: ${PWD}/docker/nginx/
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ${PWD}/data:/data
    environment:
      IMAGE_RESIZER: 127.0.0.1:8000
#      CORE: core:8000
#      STATIC: core:8000
    networks:
      - obr
    extra_hosts:
      - "host.docker.internal:host-gateway"
  image-resizer:
    container_name: obr-image-resizer
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/image-resizer/Dockerfile
    ports:
      - "8180:8000"
    volumes:
      - ${PWD}/data:/data
    environment:
      SOURCE: fs:///data/media
    networks:
      - obr
  media-encoder:
    container_name: obr-media-encoder
    user: 1000:1000
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/media-encoder/Dockerfile
    volumes:
      - ${PWD}/data:/data
  db:
    container_name: obr-db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: obr
      POSTGRES_PASSWORD: obr
    ports:
      - "5434:5432"
    volumes:
      - obr-db:/var/lib/postgresql/data
    networks:
      - obr
  core:
    container_name: obr-core
    user: 1000:1000
    command: ./manage.py runserver 0.0.0.0:8000
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/core/Dockerfile
    image: obr/core:lateest
    volumes:
      - ${PWD}/data:/data
    environment:
      DEBUG: "yes"
      DATABASE_URL: psql://obr:obr@db:5432/obr
    networks:
      - obr
    depends_on:
      - db
  sync-schedule:
    container_name: obr-sync-schedule
    user: 1000:1000
    command: ./sync-schedule
    image: obr/core:lateest
    volumes:
      - ${PWD}/data:/data
    environment:
      DATABASE_URL: psql://obr:obr@db:5432/obr
    networks:
      - obr
    depends_on:
      - db
      - core
  mailhog:
    container_name: obr-mailhog
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025" # smtp
      - "8025:8025" # ui
    networks:
      - obr
#  core:
#    container_name: obr-core
#    build:
#      context: ${PWD}
#      dockerfile: docker/Dockerfile
#    ports:
#      - "9999:8000"
#    volumes:
#      - data:/data
#    networks:
#      - obr

volumes:
  obr:
  obr-db:

networks:
  obr:
