[tool.poetry]
name = "openbroadcast.ch"
version = "0.0.1"
description = "openbroadcast.ch - next"
authors = ["Jonas Ohrstrom <jonas.ohrstrom@digris.ch>"]
license = "MIT"

packages = [
    {include="core", from="."}
]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.6"
google-cloud-secret-manager = "^2.3.0"
google-auth = "^1.28.0"
django-environ = "^0.4.5"
django-storages = {extras = ["google"], version = "^1.11.1"}
djangorestframework = "^3.12.3"
coreapi = "^2.3.3"
drf-yasg = "^1.20.0"
django-settings-export = "^1.2.1"
graphene-django = "^2.15.0"
django-filter = "^2.4.0"
graphene-django-optimizer = "^0.8.0"
Pillow = "^8.2.0"
django-admin-sortable2 = "^0.7.8"
django-cleanup = "^5.1.0"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"
django-extensions = "*"
frosted = "*"
pre-commit = "*"
prospector = "*"
pygtail = "*"
pylint = "*"
pylint-django = "*"
werkzeug = "*"
pytest-django = "*"
pytest-cov = "*"
django-querycount = "*"
Faker = "^7.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
