[tool.poetry]
name = "openbroadcast.ch"
version = "0.0.1"
description = "openbroadcast.ch - next"
authors = ["Jonas Ohrstrom <jonas.ohrstrom@digris.ch>"]
license = "MIT"

packages = [
    {include="core", from="."}
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.6"
google-cloud-secret-manager = "^2.3.0"
google-auth = "^1.28.0"
django-environ = "^0.4.5"
django-storages = {extras = ["google"], version = "^1.11.1"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
