[tool.poetry]
name = "openbroadcast.ch"
version = "0.0.1"
description = "openbroadcast.ch - next"
authors = ["Jonas Ohrstrom <jonas.ohrstrom@digris.ch>"]
license = "MIT"

packages = [{include="core", from="."}]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.9"
google-cloud-secret-manager = "^2.3.0"
google-auth = "^1.28.0"
django-environ = "^0.4.5"
django-storages = {extras = ["google"], version = "^1.11.1"}
djangorestframework = "^3.12.3"
coreapi = "^2.3.3"
django-settings-export = "^1.2.1"
django-filter = "^2.4.0"
Pillow = "^8.2.0"
# django-admin-sortable2 = "^1.0.2"
django-cleanup = "^5.1.0"
mondrian = "^0.8.1"
drf-flex-fields = "^0.9.0"
django-request-logging = "^0.7.3"
google-cloud-logging = "^2.3.1"
social-auth-app-django = "^5"
Hypercorn = "^0.12"
click = "^8.0.0"
stripe = "2.60.0"
colorthief = "^0.2.1"
django-taggit = "^1.4.0"
drf-spectacular = "^0.17.3"
filetype = "^1.0.7"
djangorestframework-camel-case = "^1.2.0"
sentry-sdk = "^1.3.1"
Markdown = "^3.3.4"
setoptconf = "^0.3.0"
whitenoise = {extras = ["brotli"], version = "^5.3.0"}
bleach = "^4.1.0"
django-countries = "^7.2.1"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"
django-extensions = "*"
frosted = "*"
pre-commit = "*"
prospector = "^1.3.1"
pygtail = "*"
pylint = "*"
pylint-django = "*"
werkzeug = "*"
pytest-django = "*"
pytest-cov = "*"
django-querycount = "*"
Faker = "^7.0.1"
django-stubs = "^1.8.0"
djangorestframework-stubs = "^1.4.0"
freezegun = "^1.1.0"
mixer = "^7.2.0"
selenium = "^4.0.0"
libfaketime = "^2.0.0"
vulture = "^2.3"
pyupgrade = "^2.29.1"
black = "^21.12b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds core.settings.test"  # term:skip-covered / term-missing
python_files = ["test_*.py"]
markers = [
    "integration: marks tests as slow (deselect with '-m \"not integration\"')",
    "e2e: marks tests as slow (deselect with '-m \"not e2e\"')",
]
filterwarnings = [
    "ignore:::standard_library",
    "ignore:::cms",
    "ignore:::html5lib",
    "ignore:::djangocms_attributes_field",
    "ignore::django.utils.deprecation.RemovedInDjango40Warning:django",
    "ignore::django.utils.deprecation.RemovedInDjango41Warning:django",
    "ignore::DeprecationWarning:future",
    "ignore::DeprecationWarning:google",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[mypy.plugins.django-stubs]
django_settings_module = "core.settings.test"
