# Generated by Django 3.2.10 on 2022-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("state", models.CharField(db_index=True, max_length=32)),
                ("obj_key", models.CharField(db_index=True, max_length=32)),
                ("source", models.CharField(db_index=True, max_length=32)),
                ("user_identity", models.CharField(db_index=True, max_length=64)),
                ("device_key", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "verbose_name": "Player event",
                "db_table": "stats_player_event",
                "ordering": ["-time"],
            },
        ),
    ]
