# Generated by Django 4.2.2 on 2023-09-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0009_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="remote_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
