# Generated by Django 5.0.7 on 2025-05-19 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming_services", "0002_syncsettings_remote_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncsettings",
            name="remote_uri",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Remote URI"
            ),
        ),
        migrations.CreateModel(
            name="RemoteMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Title"
                    ),
                ),
                (
                    "artist_name",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Artist"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("spotify", "Spotify"), ("deezer", "Deezer")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        db_index=True, max_length=256, verbose_name="Remote ID"
                    ),
                ),
                (
                    "remote_uri",
                    models.CharField(
                        db_index=True, max_length=256, verbose_name="Remote URI"
                    ),
                ),
                (
                    "remote_data",
                    models.JSONField(default=dict, verbose_name="Remote Data"),
                ),
            ],
            options={
                "verbose_name": "Media (remote)",
                "verbose_name_plural": "Media (remote)",
                "ordering": ["-updated"],
                "unique_together": {("provider", "remote_uri")},
            },
        ),
    ]
