# Generated by Django 3.1.7 on 2021-04-07 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True, editable=False, max_length=8, unique=True
                    ),
                ),
                (
                    "obj_key",
                    models.CharField(editable=False, max_length=128, null=True),
                ),
                ("time_start", models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                "verbose_name": "Emission",
                "verbose_name_plural": "Emissions",
                "ordering": ["-time_start"],
                "get_latest_by": "time_start",
            },
        ),
    ]
