# Generated by Django 3.1.7 on 2021-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="time_start",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
