# Generated by Django 3.2.4 on 2021-09-08 10:12

from django.db import migrations

import tagging.managers


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0002_alter_tag_type"),
        ("broadcast", "0006_editor_sync_last_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editor",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Editor",
                "verbose_name_plural": "Editors",
            },
        ),
        migrations.AlterField(
            model_name="editor",
            name="tags",
            field=tagging.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tagging.TaggedItem",
                to="tagging.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
