# Generated by Django 3.2.7 on 2021-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0007_auto_20210908_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="role",
            field=models.CharField(
                choices=[("music-editor", "Musikredaktion")],
                default="music-editor",
                max_length=32,
            ),
        ),
    ]
