# Generated by Django 3.2.10 on 2022-03-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0009_editor_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editor",
            options={
                "ordering": ["-is_active", "display_name"],
                "verbose_name": "Editor",
                "verbose_name_plural": "Editors",
            },
        ),
        migrations.AlterField(
            model_name="editor",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
