# Generated by Django 3.2.13 on 2022-09-07 07:59

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0010_auto_20220311_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="description_de",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="description_fr",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=96, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
    ]
