# Generated by Django 3.2.15 on 2022-10-27 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("name_en", models.CharField(max_length=64, null=True)),
                ("name_de", models.CharField(max_length=64, null=True)),
                ("name_fr", models.CharField(max_length=64, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Category",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("question", models.TextField(max_length=256)),
                ("question_en", models.TextField(max_length=256, null=True)),
                ("question_de", models.TextField(max_length=256, null=True)),
                ("question_fr", models.TextField(max_length=256, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_de", models.TextField(null=True)),
                ("answer_fr", models.TextField(null=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faq.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "ordering": ["category", "-priority", "question"],
            },
        ),
    ]
