# Generated by Django 3.1.7 on 2021-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20210407_2053"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
