# Generated by Django 3.1.7 on 2021-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_playlist_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistmedia",
            name="cue_in",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlistmedia",
            name="cue_out",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlistmedia",
            name="fade_cross",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlistmedia",
            name="fade_in",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlistmedia",
            name="fade_out",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlistmedia",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
