# Generated by Django 3.1.8 on 2021-04-17 16:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_auto_20210417_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airplay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("time_start", models.DateTimeField(db_index=True)),
                ("time_end", models.DateTimeField(db_index=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airplays",
                        to="catalog.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Airplay",
                "verbose_name_plural": "Airplays",
                "ordering": ["-time_start"],
                "get_latest_by": "time_start",
            },
        ),
    ]
