# Generated by Django 3.2.4 on 2021-06-22 15:13

import uuid

import django.db.models.deletion
from django.db import migrations, models

import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0001_initial"),
        ("catalog", "0017_auto_20210622_1403"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=256, null=True)),
            ],
            options={
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="media",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tagging.TaggedItem",
                to="tagging.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="series_episode",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Series #"
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tagging.TaggedItem",
                to="tagging.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlists",
                to="catalog.series",
                verbose_name="Series",
            ),
        ),
    ]
