# Generated by Django 3.2.4 on 2021-06-24 07:39

import datetime

import taggit.managers
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0001_initial"),
        ("catalog", "0019_auto_20210622_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tagging.TaggedItem",
                to="tagging.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
    ]
