# Generated by Django 3.2.4 on 2021-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="content_type",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="master",
            name="md5_hash",
            field=models.CharField(default="", max_length=24),
        ),
        migrations.AddField(
            model_name="master",
            name="size",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="master",
            name="encoding",
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
    ]
