# Generated by Django 3.2.4 on 2021-09-08 10:12

import django.db.models.deletion
from django.db import migrations, models

import tagging.managers


class Migration(migrations.Migration):
    dependencies = [
        ("tagging", "0002_alter_tag_type"),
        ("broadcast", "0007_auto_20210908_1212"),
        ("catalog", "0024_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="tags",
            field=tagging.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tagging.TaggedItem",
                to="tagging.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlists",
                to="broadcast.editor",
                verbose_name="Editor",
            ),
        ),
    ]
