# Generated by Django 3.2.7 on 2021-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_auto_20210908_1212"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasemedia",
            options={
                "ordering": ["position"],
                "verbose_name": "Release media",
                "verbose_name_plural": "Release media",
            },
        ),
        migrations.AddField(
            model_name="mood",
            name="animation_url",
            field=models.URLField(blank=True),
        ),
    ]
