# Generated by Django 3.2.10 on 2021-12-16 19:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_alter_master_md5_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="duration",
            field=models.DurationField(db_index=True, default=datetime.timedelta(0)),
        ),
    ]
