# Generated by Django 3.2.10 on 2022-05-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_alter_playlist_series_episode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mood",
            name="animation_url",
        ),
    ]
