# Generated by Django 3.2.13 on 2022-06-08 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_alter_mood_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="name_de",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="name_en",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="name_fr",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="teaser_de",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="teaser_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="teaser_fr",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
                editable=False,
            ),
        ),
    ]
