# Generated by Django 4.1.3 on 2023-03-23 12:51

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0034_alter_playlistmedia_options_artistimage_md5_hash_and_more"),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
