# Generated by Django 5.0.7 on 2025-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0005_alter_identifier_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="identifier",
            name="origin",
            field=models.CharField(
                choices=[("obp", "OBP"), ("crawler", "Crawler")],
                db_index=True,
                default="obp",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="scope",
            field=models.CharField(
                choices=[
                    ("musicbrainz", "Musicbrainz"),
                    ("obp", "open broadcast platform"),
                    ("discogs", "Discogs"),
                    ("wikipedia", "Wikipedia"),
                    ("soundcloud", "SoundCloud"),
                    ("official", "Website"),
                    ("isrc", "ISRC"),
                    ("spotify", "Spotify"),
                    ("deezer", "Deezer"),
                ],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Identifier scope",
            ),
        ),
    ]
