# Generated by Django 3.2.15 on 2022-11-17 10:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=256)),
                ("title", models.CharField(max_length=64)),
                ("title_en", models.CharField(max_length=64, null=True)),
                ("title_de", models.CharField(max_length=64, null=True)),
                ("title_fr", models.CharField(max_length=64, null=True)),
                ("lead", models.TextField(blank=True, default="")),
                ("lead_en", models.TextField(blank=True, default="", null=True)),
                ("lead_de", models.TextField(blank=True, default="", null=True)),
                ("lead_fr", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=64)),
                (
                    "title_en",
                    models.CharField(blank=True, default="", max_length=64, null=True),
                ),
                (
                    "title_de",
                    models.CharField(blank=True, default="", max_length=64, null=True),
                ),
                (
                    "title_fr",
                    models.CharField(blank=True, default="", max_length=64, null=True),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("text", "Plaintext"),
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                        ],
                        default="markdown",
                        max_length=32,
                        verbose_name="Content format",
                    ),
                ),
                ("body", models.TextField()),
                ("body_en", models.TextField(null=True)),
                ("body_de", models.TextField(null=True)),
                ("body_fr", models.TextField(null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["-position", "title"],
            },
        ),
    ]
