# Generated by Django 3.2.15 on 2022-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="path",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
