# Generated by Django 3.2.15 on 2022-11-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_page_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="expandable",
            field=models.BooleanField(
                default=False, help_text="if set to yes 'title' must be provided"
            ),
        ),
    ]
