# Generated by Django 3.2.16 on 2022-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_section_expandable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["position", "title"],
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="path",
            field=models.CharField(
                db_index=True, help_text="e.g. legal/terms", max_length=256, unique=True
            ),
        ),
    ]
