# Generated by Django 4.1.3 on 2023-03-30 14:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_airplay"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=250,
                        verbose_name="mountpoint",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=6,
                        verbose_name="request method",
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(blank=True, db_index=True, default=""),
                ),
                ("bytes_sent", models.PositiveIntegerField(blank=True, default="")),
                ("referer", models.CharField(blank=True, default="", max_length=500)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("time_start", models.DateTimeField(db_index=True)),
                ("time_end", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Player event",
                "db_table": "stats_stream_event",
                "ordering": ["time_start"],
            },
        ),
    ]
