# Generated by Django 4.1.3 on 2023-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0005_streamevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamevent",
            options={"ordering": ["time_start"], "verbose_name": "Stream event"},
        ),
        migrations.AddField(
            model_name="streamevent",
            name="seconds_connected",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="duration"
            ),
            preserve_default=False,
        ),
    ]
