# Generated by Django 4.1.3 on 2023-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_alter_streamevent_bytes_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="obj_key",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=128
            ),
        ),
    ]
