# Generated by Django 4.2.7 on 2024-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0010_heartbeat_remote_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartbeat",
            name="player_source",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("ondemand", "ondemand"),
                    ("unknown", "unknown"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
