# Generated by Django 4.2.7 on 2024-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0011_alter_heartbeat_player_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="device_key",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
    ]
