# Generated by Django 4.2.7 on 2024-06-26 08:25

from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0012_streamevent_device_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="geoip_city",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="streamevent",
            name="geoip_country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="streamevent",
            name="geoip_region",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="streamevent",
            name="device_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
