# Generated by Django 4.2.13 on 2024-06-26 14:44

import datetime

from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0014_alter_streamevent_geoip_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerevent",
            name="max_duration",
            field=models.DurationField(
                blank=True, db_index=True, default=datetime.timedelta(0)
            ),
        ),
        migrations.AddField(
            model_name="playerevent",
            name="time_end",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="streamevent",
            name="geoip_city",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="streamevent",
            name="geoip_country",
            field=django_countries.fields.CountryField(
                blank=True,
                db_index=True,
                default="",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="streamevent",
            name="geoip_region",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="region",
            ),
        ),
    ]
