# Generated by Django 4.2.13 on 2024-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0015_playerevent_max_duration_playerevent_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerevent",
            name="max_duration",
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
    ]
