# Generated by Django 4.2.13 on 2024-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0016_alter_playerevent_max_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerevent",
            name="state",
            field=models.CharField(
                choices=[
                    ("playing", "Playing"),
                    ("paused", "Paused"),
                    ("stopped", "Stopped"),
                    ("buffering", "Buffering"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
