# Generated by Django 5.0.7 on 2024-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0017_alter_playerevent_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerevent",
            name="calculated_duration_s",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=3, default=0, max_digits=10
            ),
        ),
    ]
