# Generated by Django 5.0.7 on 2024-11-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0018_playerevent_calculated_duration_s"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="origin",
            field=models.CharField(
                choices=[("icecast", "Icecast"), ("hls", "HLS")],
                db_index=True,
                default="icecast",
                max_length=16,
            ),
        ),
    ]
