# Generated by Django 5.0.7 on 2025-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0019_streamevent_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartbeat",
            name="player_source",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("news", "news"),
                    ("ondemand", "ondemand"),
                    ("unknown", "unknown"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="streamevent",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, db_index=True, null=True, verbose_name="client IP"
            ),
        ),
    ]
