# Generated by Django 4.1.3 on 2023-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0005_alter_vote_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
