# Generated by Django 4.1.3 on 2023-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0008_alter_vote_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("live", "live"), ("ondemand", "on demand")],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
    ]
