# Generated by Django 3.2 on 2021-05-21 17:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="extra_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
