# Generated by Django 3.2 on 2021-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_payment_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
