# Generated by Django 3.2.4 on 2021-08-10 16:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import subscription.models.voucher


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0005_alter_payment_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=subscription.models.voucher.get_default_code,
                        editable=False,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("num_days", models.PositiveIntegerField(default=7)),
                (
                    "valid_until",
                    models.DateTimeField(
                        db_index=True,
                        default=subscription.models.voucher.get_default_valid_until,
                    ),
                ),
                ("max_num_use", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Voucher",
            },
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemtions",
                        to="subscription.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Redemption",
                "verbose_name_plural": "Redemptions",
                "unique_together": {("voucher", "user")},
            },
        ),
    ]
