# Generated by Django 3.2.15 on 2022-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0009_alter_voucher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="countries_str",
            field=models.CharField(
                blank=True,
                default="CH",
                help_text="comma-separated, uppercase e.g. 'CH,FR'",
                max_length=64,
                verbose_name="Countries",
            ),
        ),
    ]
