# Generated by Django 4.1.3 on 2022-12-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0011_alter_voucher_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="max_num_use",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="num_days",
            field=models.PositiveIntegerField(default=28),
        ),
    ]
