# Generated by Django 4.1.3 on 2023-03-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0013_voucher_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="inherit",
            field=models.BooleanField(default=False),
        ),
    ]
