# Generated by Django 3.2 on 2021-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="scope",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("musicbrainz", "Musicbrainz"),
                    ("obp", "open broadcast platform"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="value",
            field=models.CharField(
                db_index=True, max_length=256, null=True, verbose_name="Identifier"
            ),
        ),
    ]
