# Generated by Django 3.2.4 on 2021-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0002_auto_20210604_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="scope",
            field=models.CharField(
                choices=[
                    ("musicbrainz", "Musicbrainz"),
                    ("obp", "open broadcast platform"),
                    ("discogs", "Discogs"),
                    ("wikipedia", "Wikipedia"),
                    ("official", "Website"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="value",
            field=models.CharField(
                db_index=True, max_length=512, null=True, verbose_name="Identifier"
            ),
        ),
    ]
