# Generated by Django 3.2.16 on 2022-12-03 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["title"],
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
            },
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="key",
        ),
    ]
