# Generated by Django 3.2.16 on 2022-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_auto_20221203_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="description",
            field=models.TextField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="description_de",
            field=models.TextField(blank=True, default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="description_en",
            field=models.TextField(blank=True, default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="description_fr",
            field=models.TextField(blank=True, default="", max_length=256, null=True),
        ),
    ]
