# Generated by Django 3.2.10 on 2022-03-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_auto_20220104_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="migration_source",
            field=models.CharField(
                choices=[
                    ("", "none"),
                    ("obr", "open broadcast - radio"),
                    ("obp", "open broadcast - platform"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
    ]
