# Generated by Django 3.2.10 on 2022-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_user_migration_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="obp_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="open broadcast - platform ID",
            ),
        ),
    ]
