# Generated by Django 3.2.13 on 2022-06-08 17:33
import datetime
import logging

from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

logger = logging.getLogger(__name__)

role_permissions = {
    "API - Sync": [
        "api_sync_webhooks",
    ],
}


# pylint: disable=unused-argument
def add_role_permissions(apps, schema_editor):
    emit_post_migrate_signal(2, False, "default")

    for r in role_permissions:
        role, created = Group.objects.get_or_create(name=r)
        logger.info(f"{r} Role retrieved")
        for p in role_permissions[r]:
            perm, created2 = Permission.objects.get_or_create(codename=p)
            role.permissions.add(perm)
            logger.info(f"Permitting {r} to {p}")
        role.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "__latest__"),
        ("account", "0017_alter_user_migration_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("api_sync_webhooks", "API - Sync webhooks"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.RunPython(add_role_permissions),
    ]
