# Generated by Django 3.2.15 on 2022-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_remove_user_gender_int"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_venue",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
