# Generated by Django 3.2.15 on 2022-10-06 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0026_user_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
    ]
