# Generated by Django 4.1.3 on 2023-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0033_alter_globalpermissions_options_alter_theme_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
