# Generated by Django 4.1.3 on 2023-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0034_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="debug_enabled",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="enable debug"
            ),
        ),
    ]
