# Generated by Django 4.2.7 on 2023-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0037_settings_testing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyuser",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legacyuser",
            name="date_last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
