# Generated by Django 4.2.7 on 2023-12-01 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0039_legacyuser_first_name_legacyuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "undefined"),
                    ("female", "female"),
                    ("male", "male"),
                    ("other", "other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="legacyuser",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="legacyuser",
            name="year_of_birth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2022),
                ],
            ),
        ),
    ]
