# Generated by Django 5.0.7 on 2025-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_alter_settings_news_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
