# Generated by Django 5.0.7 on 2025-06-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0044_user_stripe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="stripe_id",
            new_name="stripe_customer_id",
        ),
    ]
