# Generated by Django 5.0.7 on 2025-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0045_rename_stripe_id_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
