# Generated by Django 4.1.3 on 2023-01-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0006_vote_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("live", "live"), ("on-demand", "on-demand")],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
    ]
