# Generated by Django 4.1.3 on 2023-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0007_alter_vote_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="scope",
            field=models.CharField(
                choices=[
                    ("", "not specified"),
                    ("track", "track"),
                    ("emission", "emission"),
                    ("daytime", "daytime"),
                    ("repetition", "repetition"),
                    ("genre", "genre"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
            ),
        ),
    ]
