# Generated by Django 4.1.3 on 2023-03-06 13:57
from uuid import uuid4

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    pass
    Vote = apps.get_model("rating", "Vote")
    db_alias = schema_editor.connection.alias
    for vote in Vote.objects.using(db_alias).all():
        uuid = uuid4()
        uid = str(uuid)[:8].upper()
        print("UID", uid)
        Vote.objects.filter(id=vote.id).update(uuid=uuid, uid=uid)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0009_alter_vote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="vote",
            name="uid",
            field=models.CharField(
                db_index=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
