# Generated by Django 5.0.7 on 2025-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0011_alter_vote_options_alter_vote_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="origin",
            field=models.CharField(
                choices=[("user", "user"), ("sync", "sync")],
                db_index=True,
                default="user",
                max_length=16,
            ),
        ),
    ]
