# Generated by Django 3.2 on 2021-05-21 15:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0002_subscription_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initialized", "Initialized"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="State",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe")],
                        db_index=True,
                        default="stripe",
                        max_length=32,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=256,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Amount paid"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CHF", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created"],
            },
        ),
    ]
