# Generated by Django 4.1.3 on 2023-03-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0012_alter_voucher_max_num_use_alter_voucher_num_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="subscription.voucher",
                verbose_name="parent",
            ),
        ),
    ]
