# Generated by Django 4.2.7 on 2024-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_auto_20221124_2329"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="cta_title",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_title_de",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_title_en",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_title_fr",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_url_de",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_url_en",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_url_fr",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
