version: "3"
services:
  core:
    container_name: core
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    ports:
      - "9999:8000"
    volumes:
      - data:/data
    networks:
      - network

volumes:
  data:

networks:
  network:
