version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ${PWD}/docker/nginx/
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ${PWD}/data:/data
    restart: always
    networks:
      - obr
    extra_hosts:
      - "host.docker.internal:host-gateway"
  image-resizer:
    container_name: image-resizer
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/image-resizer/Dockerfile
    ports:
      - "8180:8000"
    volumes:
      - ${PWD}/data:/data
    environment:
      SOURCE: fs:///data/media
    restart: always
    networks:
      - obr
#  core:
#    container_name: core
#    build:
#      context: ${PWD}
#      dockerfile: docker/Dockerfile
#    ports:
#      - "9999:8000"
#    volumes:
#      - data:/data
#    networks:
#      - obr

volumes:
  obr:

networks:
  obr:
