# Generated by Django 3.2 on 2021-05-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_settings(apps, schema_editor):

    User = apps.get_model("account", "User")
    Settings = apps.get_model("account", "Settings")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        if not hasattr(user, "settings"):
            Settings.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auto_20210511_1811"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_settings),
    ]
