# Generated by Django 3.2.4 on 2021-08-12 09:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_user_sync_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logintoken",
            name="value",
            field=models.CharField(
                db_index=True,
                default=account.models.get_default_token,
                editable=False,
                max_length=6,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
