# Generated by Django 3.2.4 on 2021-08-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_logintoken_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_completed',
        ),
    ]
