# Generated by Django 3.2.10 on 2022-01-04 17:55
import uuid

from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    if getattr(settings, "TEST_MODE", False):
        print("TEST_MODE detected - skipping migration")
        return

    Settings = apps.get_model("account", "Settings")
    Address = apps.get_model("account", "Address")

    db_alias = schema_editor.connection.alias

    for obj in Settings.objects.using(db_alias).all():
        _uuid = uuid.uuid4()
        obj.uuid = _uuid
        obj.uid = str(_uuid)[:8].upper()
        obj.save()

    for obj in Address.objects.using(db_alias).all():
        _uuid = uuid.uuid4()
        obj.uuid = _uuid
        obj.uid = str(_uuid)[:8].upper()
        obj.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20220104_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="uid",
            field=models.CharField(
                db_index=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="settings",
            name="uid",
            field=models.CharField(
                db_index=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
