# Generated by Django 3.2.10 on 2022-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_user_obp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "undefined"), (1, "female"), (2, "male"), (3, "other")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="migration_source",
            field=models.CharField(
                choices=[
                    ("", "none"),
                    ("obr", "OBR - radio"),
                    ("obp", "OBP - platform"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
    ]
