# Generated by Django 3.2.15 on 2022-10-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_rename_gender_str_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender_int",
        ),
    ]
