# Generated by Django 3.2.15 on 2022-10-04 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_user_favorite_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="year_of_birth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2022),
                ],
            ),
        ),
    ]
