# Generated by Django 3.2.15 on 2022-10-04 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0024_user_year_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
    ]
