# Generated by Django 3.2.15 on 2022-10-06 20:32

from django.db import migrations

import django_countries.fields


def copy_country_from_address_to_user(apps, schema_editor):
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias
    qs = User.objects.using(db_alias)

    for user in qs:
        if hasattr(user, "address") and user.address.country:
            User.objects.filter(id=user.id).update(
                country=user.address.country,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_remove_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2
            ),
        ),
        migrations.RunPython(copy_country_from_address_to_user),
    ]
