# Generated by Django 3.2.16 on 2022-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_remove_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "undefined"),
                    ("female", "female"),
                    ("male", "male"),
                    ("other", "other"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
