# Generated by Django 3.2.15 on 2022-11-25 18:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("api_sync_webhooks", "API - Sync webhooks"),
                    ("api_stats_webhooks", "API - Stats webhooks"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="logintoken",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="logintoken",
            name="value",
            field=models.CharField(
                db_index=True,
                default=account.models.get_default_token,
                editable=False,
                max_length=6,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
    ]
