# Generated by Django 4.1.3 on 2023-03-07 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0030_legacyuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("api_sync_webhooks", "API - Sync webhooks"),
                    ("api_stats_view", "API - Stats view"),
                    ("api_stats_webhooks", "API - Stats webhooks"),
                ),
            },
        ),
    ]
