# Generated by Django 4.2.2 on 2023-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0036_alter_globalpermissions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="testing_enabled",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="enable testing"
            ),
        ),
    ]
