# Generated by Django 3.1.7 on 2021-04-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_auto_20210414_1550"),
        ("broadcast", "0003_emission_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="emission",
            name="time_end",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="playlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissions",
                to="catalog.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="emission",
            name="uid",
            field=models.CharField(
                db_index=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
    ]
