# Generated by Django 4.1.3 on 2023-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0011_auto_20220907_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorimage",
            name="md5_hash",
            field=models.CharField(default="", max_length=32),
        ),
    ]
