# Generated by Django 4.2.7 on 2024-06-24 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "broadcast",
            "0013_alter_editor_display_name_alter_editorimage_filename_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editorimage",
            options={
                "get_latest_by": "created",
                "ordering": ["position"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
