# Generated by Django 5.0.7 on 2025-05-21 12:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0014_alter_editorimage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="editorimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
    ]
