# Generated by Django 5.0.7 on 2025-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0015_alter_editor_sync_last_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
