# Generated by Django 5.2.6 on 2026-03-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0016_alter_editor_sync_state"),
        ("catalog", "0050_alter_artist_sync_state_alter_label_sync_state_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emission",
            index=models.Index(
                fields=["time_start", "time_end"], name="broadcast_e_time_st_dfb024_idx"
            ),
        ),
    ]
