name: GCP

on: [push]

#on:
#  workflow_run:
#    workflows: ["CI"]
#    branches: [main]
#    types:
#      - completed

env:
  IMAGE_NAME: obr-web
  GH_REGISTRY: ghcr.io
  GH_ORGANIZATION: digris
  GCP_PROJECT_ID: open-broadcast
  GCP_SERVICE: obr-web

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    if: github.ref == 'refs/heads/main'
#    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # prepare github
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # prepare GCP
      - name: GCP auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Authorize Docker push
        run: gcloud auth configure-docker

#      - name: Submit to cloudbuild
#        run: gcloud builds submit --async

      # build & push image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#        with:
#          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Extract metadata (tags, labels) for image
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.GH_ORGANIZATION }}/${{ env.IMAGE_NAME }}
            gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#          tags: |
#            gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}:${{ github.sha }}

      - name: Deploy to GCP cloud run
        run: gcloud builds submit --config gcp/migrate-deploy.yaml --timeout=1200 --async
