name: Mirror to gitlab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for proper mirroring

      - name: Set up SSH key for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push all branches and tags to GitLab
        run: |
          git remote add gitlab git@gitlab.com:digris/open-broadcast/openbroadcast.ch.git
          git push --mirror gitlab
