# Generated by Django 3.1.7 on 2021-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_auto_20210409_2336"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
