# Generated by Django 3.1.8 on 2021-04-17 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_auto_20210417_1618"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="releasemedia",
            unique_together={("release", "media")},
        ),
    ]
