# Generated by Django 3.2 on 2021-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_airplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistimage",
            name="colors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlistimage",
            name="colors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releaseimage",
            name="colors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
