# Generated by Django 3.2.4 on 2021-06-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0005_editor_editorimage"),
        ("catalog", "0018_auto_20210622_1713"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={
                "ordering": ["name"],
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="broadcast.editor",
                verbose_name="Editor",
            ),
        ),
    ]
