# Generated by Django 3.2.10 on 2022-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0028_alter_media_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="series_episode",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Series #"
            ),
        ),
    ]
