# Generated by Django 3.2.10 on 2022-05-09 16:08

from django.db import migrations, models


def get_default_style():
    return {
        "color": [128, 128, 128],
    }


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0030_remove_mood_animation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="style",
            field=models.JSONField(default=get_default_style),
        ),
    ]
