# Generated by Django 4.2.7 on 2023-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0036_alter_artist_country_code_alter_artistimage_filename_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artistimage",
            options={
                "get_latest_by": "created",
                "ordering": ["position"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterModelOptions(
            name="playlistimage",
            options={
                "get_latest_by": "created",
                "ordering": ["position"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterModelOptions(
            name="releaseimage",
            options={
                "get_latest_by": "created",
                "ordering": ["position"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AddField(
            model_name="media",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("song", "Song"),
                    ("acappella", "A cappella"),
                    ("soundeffects", "Sound effects"),
                    ("soundtrack", "Soundtrack"),
                    ("spokenword", "Spokenword"),
                    ("interview", "Interview"),
                    ("jingle", "Jingle"),
                    ("djmix", "DJ-Mix"),
                    ("concert", "Concert"),
                    ("liveact", "Live Act PA)"),
                    ("radioshow", "Radio show"),
                ],
                db_index=True,
                default="",
                max_length=16,
            ),
        ),
    ]
