# Generated by Django 5.0.7 on 2025-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_release_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="date_end",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="date_start",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
