# Generated by Django 5.0.7 on 2025-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_label_date_end_label_date_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("major", "Major label"),
                    ("independent", "Independent label"),
                    ("netlabel", "Netlabel"),
                    ("event", "Event label"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artistimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="labelimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="playlistimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="releaseimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
    ]
