# Generated by Django 5.0.7 on 2025-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_label_kind_alter_artistimage_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("major", "Major label"),
                    ("independent", "Independent label"),
                    ("net", "Netlabel"),
                    ("event", "Event label"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
            ),
        ),
    ]
