# Generated by Django 5.0.7 on 2025-02-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_alter_label_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="catalog.label",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("major", "Major"),
                    ("independent", "Independent"),
                    ("net", "Netlabel"),
                    ("event", "Event"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
                verbose_name="label type",
            ),
        ),
    ]
