# Generated by Django 5.0.7 on 2025-05-19 18:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_media_lyrics_explicit_media_lyrics_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="lyrics_explicit",
            field=models.IntegerField(
                choices=[(0, "Clean"), (1, "Explicit")],
                db_index=True,
                default=0,
                verbose_name="Explicit lyrics",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="lyrics_language",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=5,
                verbose_name="Lyrics language",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="lyrics_text",
            field=models.TextField(blank=True, default="", verbose_name="Lyrics"),
        ),
        migrations.AlterField(
            model_name="media",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="sync_last_update",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Last sync",
            ),
        ),
    ]
