# Generated by Django 5.0.7 on 2025-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_alter_artist_sync_last_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="license",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unknown"),
                    ("independent", "Independent"),
                    ("major", "Major"),
                    ("major_root", "Major (inherited)"),
                ],
                db_index=True,
                default="unknown",
                max_length=16,
                verbose_name="license",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("independent", "Independent"),
                    ("major", "Major"),
                    ("net", "Netlabel"),
                    ("event", "Event"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
                verbose_name="label type",
            ),
        ),
    ]
