# Generated by Django 5.0.7 on 2025-05-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0047_label_license_alter_label_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="license",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unknown"),
                    ("independent", "Independent"),
                    ("major", "Major"),
                    ("major_root", "Major (inherited)"),
                ],
                db_index=True,
                default="unknown",
                editable=False,
                max_length=16,
                verbose_name="license",
            ),
        ),
    ]
