# Generated by Django 5.0.7 on 2025-05-21 13:17

from django.db import migrations, models


def lyrics_explicit_int_to_text(apps, schema_editor):
    Media = apps.get_model("catalog", "Media")
    db_alias = schema_editor.connection.alias

    Media.objects.using(db_alias).filter(lyrics_explicit="0").update(
        lyrics_explicit="clean"
    )
    Media.objects.using(db_alias).filter(lyrics_explicit="1").update(
        lyrics_explicit="explicit"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_media_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="lyrics_explicit",
            field=models.CharField(
                choices=[("clean", "Clean"), ("explicit", "Explicit")],
                db_index=True,
                default="clean",
                max_length=16,
                verbose_name="Explicit lyrics",
            ),
        ),
        migrations.RunPython(
            lyrics_explicit_int_to_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
