# Generated by Django 5.0.7 on 2025-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0049_alter_media_lyrics_explicit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("song", "Song"),
                    ("acappella", "A cappella"),
                    ("soundeffects", "Sound effects"),
                    ("soundtrack", "Soundtrack"),
                    ("spokenword", "Spokenword"),
                    ("interview", "Interview"),
                    ("jingle", "Jingle"),
                    ("djmix", "DJ-Mix"),
                    ("concert", "Concert"),
                    ("liveact", "Live Act PA)"),
                    ("radioshow", "Radio show"),
                    ("news", "News"),
                ],
                db_index=True,
                default="",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
